---

- hosts: webservers
  become: true
  tasks:

  - name: Install NGINX package
    package:
      name:
        - nginx
        - net-tools
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: Start NGINX service
    systemd:
      state: started
      name: nginx
      enabled: yes
    when: ansible_distribution == "Ubuntu"
