---

- hosts: webservers
  become: true
  tasks:

  - name: Upgrade dist packages
    apt:
      upgrade: dist

  - name: Install NGINX package
    apt:
      name: nginx
      state: latest
  
  - name: Start NGINX service
    systemd:
      state: started
      name: nginx
      enabled: yes
