---

- hosts: webservers
  become: true
  tasks:

  - name: Install NGINX package
    tags: nginx,web,webserver,package
    package:
      name:
        - "{{ nginx_package }}"
        - net-tools
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: Start NGINX service
    tags: proccess,nginx,webserver,web
    systemd:
      state: started
      name: nginx
      enabled: yes
    when: ansible_distribution == "Ubuntu"
