---
- hosts: localhost
  become: true
  tasks:


  - name: Install Unzip
    tags: arch, unzip, package
    package:
      name: unzip

  - name: Install Terraform
    tags: terraform, package
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0777
