---

- hosts: webservers
  become: true
  tasks:

  - name: Stop NGINX service
    systemd:
      name: nginx
      state: stopped

  - name: Remove NGINX package
    apt:
      name: nginx
      state: absent
      purge: yes
  

